[workspace]
resolver = "3"
members = [
  "crates/authentication",
  "crates/authorization",
  "crates/codec",
  "crates/crypto",
  "crates/domain",
  "crates/domain-derive",
  "crates/logic"
]

[workspace.dependencies]
alternate-domain-derive.path = "crates/domain-derive"
alternate-logic.path = "crates/logic"

nutype = "0.8.0-beta.2"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
tracing = "0.1.44"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
must_use_candidate = "allow"
unused_async_trait_impl = "allow"