[package]
name = "alternate-domain-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.24.1"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.6"
proc-macro-crate = "3.5.0"

[dev-dependencies]
syn = { version = "3.0.6", features = ["full"] }

[lints]
workspace = true
