[package]
name = "alternate-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = { version = "0.2.37", optional = true, default-features = false }
nutype = "0.8.0-beta.2"
thiserror.workspace = true
uuid = { version = "1.26.1", optional = true, default-features = false }

[features]
default = []
jiff = ["dep:jiff"]
uuid = ["dep:uuid"]

[lints]
workspace = true
