[package]
name = "alternate-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
alternate-domain-derive.workspace = true
alternate-validation.workspace = true

jiff = { version = "0.2.37", optional = true, default-features = false }
thiserror.workspace = true
uuid = { version = "1.26.1", optional = true, default-features = false }

[features]
default = []
email-address = ["alternate-validation/email-address"]
jiff = ["dep:jiff"]
url = ["alternate-validation/url"]
uuid = ["dep:uuid"]

[lints]
workspace = true
