[package]
name = "alternate-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = { version = "0.23.1", optional = true }
blake3 = { version = "1.8.7", optional = true }
hex = { version = "0.4.3", optional = true }
rand = { version = "0.10.2", optional = true }
sha2 = { version   = "0.11.0", optional = true }
thiserror.workspace = true

[features]
default = []
base64 = ["encoding", "dep:base64"]
blake3 = ["digest", "dep:blake3"]
csprng = ["dep:rand"]
digest = ["dep:blake3"]
encoding = []
hex = ["encoding", "dep:hex"]
sha256 = ["digest", "dep:sha2"]

[lints]
workspace = true
